### ISSUE TITLE
plot distribution of reservoir size along downstream path

### ISSUE THREAD

**Issue by jmigueldelgado** [SophiaDobko/assimReservoirs#14]
cluster these distributions by size of starting reservoir and evaluate result

**Comment by SophiaDobko** [comment]
![reservoir_distribution](https://user-images.githubusercontent.com/35838674/58160276-6a245400-7c7e-11e9-9ed7-d3d688882033.png)
a first try (see script analyse_reservoir_size_distribution).
the reservoir size  and the downstream reservoir size are transformed with log10 and the clusters are formed by kmeans(...)
The x-axis shows log10(downstream reservoir size).

**Comment by SophiaDobko** [comment]
so far it seems that there is a stronger difference between the reservoir distribution of different hydrographic units than between different size classes of reservoirs, see folder ```figures``` and the script ```Analyse_reservoir_distribution``` in this repository.
