### ISSUE TITLE
replace otto basins level 6 by hydrosheds

### ISSUE THREAD

**Issue by jmigueldelgado** [SophiaDobko/assimReservoirs#2]
Hi Sophia,

after going through some databases I found out that https://hydrosheds.org/pages/overview has better resolution that the data we have been working on. It also uses the pfaffstaeter classification, so it will be easy to replace the dataset. I downloaded it and stored it on https://boxup.uni-potsdam.de/index.php/s/gWKXPC1UJlutZoG , the same folder that we used for sharing river network and topology previously.

There is even a field in the attribute table with the id number of the downstream subbasins. This makes it very easy to select all the upstream subbasins with standard filter operations.

thanks!
jose

**Comment by SophiaDobko** [comment]
ok, hydrosheds is implemented
