### ISSUE TITLE
improve recognition of strategic reservoirs

### ISSUE THREAD

**Issue by SophiaDobko** [SophiaDobko/assimReservoirs#3]
Some reservoirs are not recognized as being on the main river because have a small intersection with a lower subbasin, without receiving water from that subbasin. Therefore, up_cells from the river reach seems to be smaller than the contributing basin.

See example [hier](https://github.com/SophiaDobko/assimReservoirs/blob/master/recognize_strategic_res.pdf), green circles indicate non-recognized strategic reservoirs.

**Comment by jmigueldelgado** [comment]
I suggest relaxing the constraint `A_upcells > A_subbasin` into something like `A_upcells > 0.5*A_subbasin`. This would mean that upcells must be at least half of the subbasin, which would include:
- reservoirs that right now a missed but are strategic
- reservoirs in headwater catchments which are collecting areas from areas larger than half the subbasin's area (which is fine)

**Comment by SophiaDobko** [comment]
Ok, I tried it.
This way we get for reservoir 44755 150 strategic reservoirs, which is around half of all reservoirs in the catchment. Only one reservoir which was not recongized before still isn't, but thats a quite small one.
You can see the result [here](https://github.com/SophiaDobko/assimReservoirs/blob/hydroSheds/recognize_strategic_res2.pdf).
Now some reservoir are attributed as strategic which actually are at the very end of a certain river reach, but maybe that's no problem.
